apiVersion: v1
kind: Config
clusters:
- name: "zl"
  cluster:
    server: "https://rancher.cnzhonglunnet.com/k8s/clusters/c-s75t4"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoekNDQ\
      VM2Z0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpFdwpNVEE0TURjME5qSXlXaGNOTXpFd01UQTJNRGMwTmpJeVdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVMrNGpEeTJqNmt6T\
      mRkZTdLcll6WXIwaUQ3ZEZMNTRTZDBYN3NUZHFaVApLVXBYZmx3Mzl4enBtZFBJY01qcmNVTUlTS\
      WZ0VUhkcHdwQkRNQVhxOEJyR295TXdJVEFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFLQmdncWhrak9QUVFEQWdOSEFEQkVBaDhKVXNrcmFzRnYKS0RKQTJnOTlQT\
      mRXL2pGbm9OSE4rSUgzYzJ2Yjgzb0xBaUVBenRwYXN2RGxvOHRKcjVmNG9qZHlWQm9ocGwzegp6W\
      UlUNi9MLzNOSlJyK0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
- name: "zl-m4"
  cluster:
    server: "https://192.168.3.124:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl4TURFd09UQTJNamd3T1ZvWERUTXhNREV3TnpBMk1qZ3dPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU4yNnl2N3grVEFVCitsdDJ4a25RVFRibk1tdkl0QUYwNEJkaDZPdjRTYzgvQ0RVeUZ4Y2g3V\
      S9ORFpPa083VkxCeC9lTzM0N1BxTVAKOVlRdFJRbmhpcUFzTUVJSkFtK2xoc20zSWhWeXJlK1Z4M\
      1FObzVRczJuM2RIamMvR0tFV25xMjFabzYwL0hRMAovVmd3NUNsTGc0WWFLMFpERnpxbENPSzlFN\
      GhrMWNlblkySmh0RVZXbzhZREJYUTkwcVgxMElOMmdKTFBzSUVNClQwbXJGV2d5T2NjTlM5VHFxO\
      HdROGdFNDNBRjhVVTdwVE1yOWtDN2YyNDBraXk1RnFLZHVTYSsyelJoc0FMa3EKcS9QVVhXb1kxa\
      UtxZHlVN1RmRnA1U3NXdkZHbHEyMXY4M2hFY2lhcG1uaGdjYXVOb0VzK2hUQVc2ZXNnanpFbAo0d\
      WI3dWdpZmVEa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0E4eFNGTzd6bE5xam9xcmFuYlA2M\
      jRvdU9yc0dTMWxyZDMKWTMwV01JQkpsUnNTN20yb2NqSG13c04xTC96UEg1ekIwK2twRFUvMUVKd\
      UJmcVZqWnFVajVmaWRlNE12QjhQeQo5Q2lXSGpXbTlZN3ZlQ1pYQWRzS3RXUkIvWnNDVm1VU2NIU\
      Hk1eUF4aW9JTDhlOWFHVmhTU1VuMFFmZEpwVjBxCkJLaFlYUXJjbW8vVS95YUw5aEgxQWkxQWxya\
      nZ6aFpVSHpuaFQwRXpLd1oxZERzZkR0VmlCMkVDUllQdE51c3AKN20vYmp1M29IQUh5R2VGYmU3a\
      XRqUjFLeG43WkY3bXU3NitxTjNCa3hIYjFGb3lZK29zSUduYm1TbkpwTVZlbQo0TnRFTUxPMkpsL\
      0k5TnZkNFZYSjRsNmw4dnA0WHhtT0tyTlo1a2dkRE9RbVhKVVhVeVE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "zl-m5"
  cluster:
    server: "https://192.168.3.125:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl4TURFd09UQTJNamd3T1ZvWERUTXhNREV3TnpBMk1qZ3dPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU4yNnl2N3grVEFVCitsdDJ4a25RVFRibk1tdkl0QUYwNEJkaDZPdjRTYzgvQ0RVeUZ4Y2g3V\
      S9ORFpPa083VkxCeC9lTzM0N1BxTVAKOVlRdFJRbmhpcUFzTUVJSkFtK2xoc20zSWhWeXJlK1Z4M\
      1FObzVRczJuM2RIamMvR0tFV25xMjFabzYwL0hRMAovVmd3NUNsTGc0WWFLMFpERnpxbENPSzlFN\
      GhrMWNlblkySmh0RVZXbzhZREJYUTkwcVgxMElOMmdKTFBzSUVNClQwbXJGV2d5T2NjTlM5VHFxO\
      HdROGdFNDNBRjhVVTdwVE1yOWtDN2YyNDBraXk1RnFLZHVTYSsyelJoc0FMa3EKcS9QVVhXb1kxa\
      UtxZHlVN1RmRnA1U3NXdkZHbHEyMXY4M2hFY2lhcG1uaGdjYXVOb0VzK2hUQVc2ZXNnanpFbAo0d\
      WI3dWdpZmVEa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0E4eFNGTzd6bE5xam9xcmFuYlA2M\
      jRvdU9yc0dTMWxyZDMKWTMwV01JQkpsUnNTN20yb2NqSG13c04xTC96UEg1ekIwK2twRFUvMUVKd\
      UJmcVZqWnFVajVmaWRlNE12QjhQeQo5Q2lXSGpXbTlZN3ZlQ1pYQWRzS3RXUkIvWnNDVm1VU2NIU\
      Hk1eUF4aW9JTDhlOWFHVmhTU1VuMFFmZEpwVjBxCkJLaFlYUXJjbW8vVS95YUw5aEgxQWkxQWxya\
      nZ6aFpVSHpuaFQwRXpLd1oxZERzZkR0VmlCMkVDUllQdE51c3AKN20vYmp1M29IQUh5R2VGYmU3a\
      XRqUjFLeG43WkY3bXU3NitxTjNCa3hIYjFGb3lZK29zSUduYm1TbkpwTVZlbQo0TnRFTUxPMkpsL\
      0k5TnZkNFZYSjRsNmw4dnA0WHhtT0tyTlo1a2dkRE9RbVhKVVhVeVE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "zl-m2"
  cluster:
    server: "https://192.168.3.122:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl4TURFd09UQTJNamd3T1ZvWERUTXhNREV3TnpBMk1qZ3dPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU4yNnl2N3grVEFVCitsdDJ4a25RVFRibk1tdkl0QUYwNEJkaDZPdjRTYzgvQ0RVeUZ4Y2g3V\
      S9ORFpPa083VkxCeC9lTzM0N1BxTVAKOVlRdFJRbmhpcUFzTUVJSkFtK2xoc20zSWhWeXJlK1Z4M\
      1FObzVRczJuM2RIamMvR0tFV25xMjFabzYwL0hRMAovVmd3NUNsTGc0WWFLMFpERnpxbENPSzlFN\
      GhrMWNlblkySmh0RVZXbzhZREJYUTkwcVgxMElOMmdKTFBzSUVNClQwbXJGV2d5T2NjTlM5VHFxO\
      HdROGdFNDNBRjhVVTdwVE1yOWtDN2YyNDBraXk1RnFLZHVTYSsyelJoc0FMa3EKcS9QVVhXb1kxa\
      UtxZHlVN1RmRnA1U3NXdkZHbHEyMXY4M2hFY2lhcG1uaGdjYXVOb0VzK2hUQVc2ZXNnanpFbAo0d\
      WI3dWdpZmVEa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0E4eFNGTzd6bE5xam9xcmFuYlA2M\
      jRvdU9yc0dTMWxyZDMKWTMwV01JQkpsUnNTN20yb2NqSG13c04xTC96UEg1ekIwK2twRFUvMUVKd\
      UJmcVZqWnFVajVmaWRlNE12QjhQeQo5Q2lXSGpXbTlZN3ZlQ1pYQWRzS3RXUkIvWnNDVm1VU2NIU\
      Hk1eUF4aW9JTDhlOWFHVmhTU1VuMFFmZEpwVjBxCkJLaFlYUXJjbW8vVS95YUw5aEgxQWkxQWxya\
      nZ6aFpVSHpuaFQwRXpLd1oxZERzZkR0VmlCMkVDUllQdE51c3AKN20vYmp1M29IQUh5R2VGYmU3a\
      XRqUjFLeG43WkY3bXU3NitxTjNCa3hIYjFGb3lZK29zSUduYm1TbkpwTVZlbQo0TnRFTUxPMkpsL\
      0k5TnZkNFZYSjRsNmw4dnA0WHhtT0tyTlo1a2dkRE9RbVhKVVhVeVE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "zl-m1"
  cluster:
    server: "https://192.168.3.121:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl4TURFd09UQTJNamd3T1ZvWERUTXhNREV3TnpBMk1qZ3dPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU4yNnl2N3grVEFVCitsdDJ4a25RVFRibk1tdkl0QUYwNEJkaDZPdjRTYzgvQ0RVeUZ4Y2g3V\
      S9ORFpPa083VkxCeC9lTzM0N1BxTVAKOVlRdFJRbmhpcUFzTUVJSkFtK2xoc20zSWhWeXJlK1Z4M\
      1FObzVRczJuM2RIamMvR0tFV25xMjFabzYwL0hRMAovVmd3NUNsTGc0WWFLMFpERnpxbENPSzlFN\
      GhrMWNlblkySmh0RVZXbzhZREJYUTkwcVgxMElOMmdKTFBzSUVNClQwbXJGV2d5T2NjTlM5VHFxO\
      HdROGdFNDNBRjhVVTdwVE1yOWtDN2YyNDBraXk1RnFLZHVTYSsyelJoc0FMa3EKcS9QVVhXb1kxa\
      UtxZHlVN1RmRnA1U3NXdkZHbHEyMXY4M2hFY2lhcG1uaGdjYXVOb0VzK2hUQVc2ZXNnanpFbAo0d\
      WI3dWdpZmVEa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0E4eFNGTzd6bE5xam9xcmFuYlA2M\
      jRvdU9yc0dTMWxyZDMKWTMwV01JQkpsUnNTN20yb2NqSG13c04xTC96UEg1ekIwK2twRFUvMUVKd\
      UJmcVZqWnFVajVmaWRlNE12QjhQeQo5Q2lXSGpXbTlZN3ZlQ1pYQWRzS3RXUkIvWnNDVm1VU2NIU\
      Hk1eUF4aW9JTDhlOWFHVmhTU1VuMFFmZEpwVjBxCkJLaFlYUXJjbW8vVS95YUw5aEgxQWkxQWxya\
      nZ6aFpVSHpuaFQwRXpLd1oxZERzZkR0VmlCMkVDUllQdE51c3AKN20vYmp1M29IQUh5R2VGYmU3a\
      XRqUjFLeG43WkY3bXU3NitxTjNCa3hIYjFGb3lZK29zSUduYm1TbkpwTVZlbQo0TnRFTUxPMkpsL\
      0k5TnZkNFZYSjRsNmw4dnA0WHhtT0tyTlo1a2dkRE9RbVhKVVhVeVE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "zl-m3"
  cluster:
    server: "https://192.168.3.123:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl4TURFd09UQTJNamd3T1ZvWERUTXhNREV3TnpBMk1qZ3dPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU4yNnl2N3grVEFVCitsdDJ4a25RVFRibk1tdkl0QUYwNEJkaDZPdjRTYzgvQ0RVeUZ4Y2g3V\
      S9ORFpPa083VkxCeC9lTzM0N1BxTVAKOVlRdFJRbmhpcUFzTUVJSkFtK2xoc20zSWhWeXJlK1Z4M\
      1FObzVRczJuM2RIamMvR0tFV25xMjFabzYwL0hRMAovVmd3NUNsTGc0WWFLMFpERnpxbENPSzlFN\
      GhrMWNlblkySmh0RVZXbzhZREJYUTkwcVgxMElOMmdKTFBzSUVNClQwbXJGV2d5T2NjTlM5VHFxO\
      HdROGdFNDNBRjhVVTdwVE1yOWtDN2YyNDBraXk1RnFLZHVTYSsyelJoc0FMa3EKcS9QVVhXb1kxa\
      UtxZHlVN1RmRnA1U3NXdkZHbHEyMXY4M2hFY2lhcG1uaGdjYXVOb0VzK2hUQVc2ZXNnanpFbAo0d\
      WI3dWdpZmVEa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0E4eFNGTzd6bE5xam9xcmFuYlA2M\
      jRvdU9yc0dTMWxyZDMKWTMwV01JQkpsUnNTN20yb2NqSG13c04xTC96UEg1ekIwK2twRFUvMUVKd\
      UJmcVZqWnFVajVmaWRlNE12QjhQeQo5Q2lXSGpXbTlZN3ZlQ1pYQWRzS3RXUkIvWnNDVm1VU2NIU\
      Hk1eUF4aW9JTDhlOWFHVmhTU1VuMFFmZEpwVjBxCkJLaFlYUXJjbW8vVS95YUw5aEgxQWkxQWxya\
      nZ6aFpVSHpuaFQwRXpLd1oxZERzZkR0VmlCMkVDUllQdE51c3AKN20vYmp1M29IQUh5R2VGYmU3a\
      XRqUjFLeG43WkY3bXU3NitxTjNCa3hIYjFGb3lZK29zSUduYm1TbkpwTVZlbQo0TnRFTUxPMkpsL\
      0k5TnZkNFZYSjRsNmw4dnA0WHhtT0tyTlo1a2dkRE9RbVhKVVhVeVE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "zl"
  user:
    token: "kubeconfig-u-2ppw982ndx:d4q7chfb6cggpmlrkb78nwc8qc9wd4jvj5llpgwgchgn95c86w6hkt"


contexts:
- name: "zl"
  context:
    user: "zl"
    cluster: "zl"
- name: "zl-m4"
  context:
    user: "zl"
    cluster: "zl-m4"
- name: "zl-m5"
  context:
    user: "zl"
    cluster: "zl-m5"
- name: "zl-m2"
  context:
    user: "zl"
    cluster: "zl-m2"
- name: "zl-m1"
  context:
    user: "zl"
    cluster: "zl-m1"
- name: "zl-m3"
  context:
    user: "zl"
    cluster: "zl-m3"

current-context: "zl"
